# Header
menu:
  home: /
  about: /about
  contact: /contact

# Content
excerpt_link: ...
fancybox: true

# Sidebar
sidebar: right
widgets:
- links
- category
- tagcloud

# Links
links:
  about.me: http://about.me/mitchitized/
  linkedin: http://linkedin.com/in/mitchpirtle/
  bowery: http://bowery.io/
  slideshare: http://www.slideshare.net/spacemonkeylabs

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: mitchitized
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: 

# Baidu share
baidushare: false

# scrollUp 样式
scrollUp: image

# social
social:
  github: https://github.com/spacemonkey
  weibo: